name: Build and Push Docker Image

on:
  push:
    branches: [main]          # triggers on every push to main
    paths-ignore:
      - 'README.md'
      - 'MAINTAINERS.md'

jobs:
  build:
    runs-on: self-hosted      # runs on YOUR machine (has the bags)
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hungn252
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ghcr.io/hungn252/slam-suite:latest
            ghcr.io/hungn252/slam-suite:${{ github.sha }}
